baseURL = 'https://buglil.github.io/pycchio.it-hugo/'
languageCode = 'en-us'
title = 'Pycchio.it'

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

  [markup.highlight]
    style = "onedark"
    lineNos = true
    noClasses = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about-me/"
    weight = 4

[params]
  author = "Lorenzo Bugli"
  description = "Software engineer sharing knowledge and experiences."
  avatar = "images/avatar.png"
  bio = "Software engineer sharing knowledge and experiences about software architecture, and how to build things."
  dateFormat = "Jan 2, 2006"

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/BugliL"
    icon = "github"

  [[params.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/buglil"
    icon = "linkedin"